# fly.toml app configuration file generated for meme-bot on 2025-01-08T19:02:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'meme-bot'
primary_region = 'ord'

[build]

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
